blogsite/blogapp/urls.py
from django.urls import path, include
from . import views

app_name = 'blogapp' # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
	path('add_comment/<int:blog_pk>/', views.add_comment, name='add_comment'),
	path('add_blogpost/', views.add_blogpost, name='add_blogpost'),

#not sure what foreignkey we're passing there
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blogsite/blogsite/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')) # Note: all your app urls will start with this path
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blogsite/blogapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models

class Blogpost(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=250)
	body = models.TextField()
	timestamp = models.DateTimeField(default=datetime.now())
	
	# pub_date = models.DateTimeField()


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	blogpost = models.ForeignKey(Blogpost, on_delete=models.CASCADE, related_name='comments')
	body = models.CharField(max_length= 25000)
	timestamp= models.DateTimeField(default=datetime.now())

blogsite/blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse
from .models import Blogpost, Comment
from django.contrib.auth.decorators import permission_required

def index(request):
    blogpost_list = Blogpost.objects.all()
    comments = Comment.objects.all()
    return render(request,'blogapp/index.html', {'blogposts':blogpost_list, 'comment':comments})

#we need to figure out where the incoming text is from if this is a pure "put thing is a pure post command
#whelp we just made a fuckton of new links on this page
@permission_required('comments.can_post')
def add_comment(request, blog_pk): #commentid
    blog = get_object_or_404(Blogpost, pk=blog_pk)
    commenttext = request.POST['comment_text']
    comment_entry = Comment(user= request.user, blogpost = blog, body = commenttext, )
    comment_entry.save()
    return redirect(reverse('blogapp:index'))
#this view passes comment info from template to models

#so comment_entry is gonna be good forblogpost


# do we have the views written to take comment text and send it to be back end?
# do we have the veiws written to take the 

@permission_required('blogpost.can_post')
def add_blogpost(request):
    if request.method == 'POST':
        blog_body = request.POST['blog_text']
        blog_title = request.POST['title']
        blog_entry = Blogpost(user = request.user, body = blog_body, title = blog_title)
        blog_entry.save()
    return redirect(reverse('blogapp:index'))
    # return redirect(reverse('blogapp:index'))

blogsite/blogapp/templates/blogapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
    {% block title %}{% endblock %}
  </title>

    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>

    {% block styles %}{% endblock styles %}
</head>
<body>
  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>

    {% block content %}
    {% endblock %}
</body>
</html>

blogsite/blogapp/templates/blogapp/comment.html
<h1>{{ comment.title }}</h1>
{{ comment.body }}
{{ comment.timestamp }}

blogsite/blogapp/templates/blogapp/comment_form.html
<form action="/action_page.php">
  Comment:<br>
  <input type="text" name="comment" value=""><br><br>
  <input type="submit" value="Submit">
</form>

{# this is actively not connected, we might consider giving comment_form it's own html to inhereit at some point, but that also means the connections between this and templates and views #}

blogsite/blogapp/templates/blogapp/index.html
{% extends 'blogapp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<p>We Get What We Deserve</p>


  {% for post in blogposts %} 
     {{post.id}}
    {% include "blogapp/post.html" with blogpost=post %}

  {% if user.is_authenticated %}
    <h1>submit a comment</h1>
    <form action="{% url 'blogapp:add_comment' blog_pk=post.pk %}" method="post">
        {% csrf_token %}
      <input type="text" name="comment_text"/>
      <button type="submit">Submit Comment</button>
    </form>

    {% for comment in post.comments.all %}
      {% include "blogapp/comment.html" with comment=comment %}
    {% endfor %}
  {% endif %}
{% endfor %}

{% endblock %}

blogsite/blogapp/templates/blogapp/post.html
<h1>{{ blogpost.title }}</h1>{
{{ blogpost.body }}
<h2>post a blogpost</h2>

{% if user.is_authenticated %}
    <form action="{% url 'blogapp:add_blogpost'%}" method="post">
        {% csrf_token %}
      <input type="text" name="title" />
      <input type="text" name="blog_text"/>
      <button type="submit">Submit Blog</button>
    </form>
{% endif %}

blogsite/templates/base_generic.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
</head>
<body>
    <h1>{% block title %}{% endblock %}</h1>
    <hr/>
    {% block content %}
    {% endblock %}
    <hr/>
    (c) myapp inc
</body>

<ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>

</body>

</html>